services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api-server
      - graphql-server
    volumes:
      - .:/app
    working_dir: /app/apps/web
    networks:
      - internal

  api-server:
    build:
      context: .
      dockerfile: packages/api-server/Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - .:/app
    working_dir: /app/packages/api-server
    networks:
      - internal     

  graphql-server:
    build:
      context: .
      dockerfile: packages/graphql-server/Dockerfile
    ports:
      - "4002:4002"
    volumes:
      - .:/app
    working_dir: /app/packages/graphql-server
    networks:
      - internal

  nginx:
    build:
      context: ./packages/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - internal

networks:
  internal:
    driver: bridge
