export const NAMES = [
  "Ashen Banner Compact",
  "Black Salt Brotherhood",
  "Blood Lantern Coven",
  "Brass Seraph Syndicate",
  "Children of the Thorn",
  "Cindercloak League",
  "Circle of the Verdant Maw",
  "Clockwork Penitents",
  "Crimson Oath Mercatoria",
  "Dawnbreak Palatine",
  "Drowned Cathedral",
  "Ebon Sun Cartel",
  "Emberward Communion",
  "Feral Star Nomads",
  "Gilded Rook Company",
  "Glass Moon Concord",
  "Gravetide Fellowship",
  "Greywild Rangers",
  "Hollow Crown Conclave",
  "Iron Sable Coalition",
  "Ivory Myriad",
  "Jade Reef Armada",
  "Last Hearth Compact",
  "League of the Sundered Map",
  "Lilac Veil Sisterhood",
  "Luminous Spire Custodians",
  "Marrowborne Parliament",
  "Mirewalk Covenant",
  "Nocturne Vigil",
  "Obsidian Ledger",
  "Order of the Broken Antler",
  "Order of Salt and Smoke",
  "Pale Throne Wardens",
  "Red Thistle Compact",
  "Runeharrow Keepers",
  "Sable Compass Guild",
  "Saltpetre Syndicate",
  "Scab Choir",
  "Shatterglass Templars",
  "Silent Orchard",
  "Silver Lament Navigators",
  "Skygrave Corsairs",
  "Smoke & Laurel Society",
  "Thirteenth Lantern",
  "Umbral Loom Cabal",
  "Verdigris Covenant",
  "Violet Sark Brigade",
  "Wardenry of the Drowned Bell",
  "Wayward Crown Freeholders",
  "Yew & Iron Fellowship",
];

export const RACES = [
  "Human",
  "Elf",
  "Dwarf",
  "Half-Orc",
  "Goblin",
  "Halfling",
  "Multiracial",
];
