name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-testing:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Restore turbo cache
        id: turbo-cache
        uses: actions/cache/restore@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Lint
        run: npx turbo run lint --cache-dir=.turbo

      - name: Type check
        run: npx turbo run check-types --cache-dir=.turbo

      - name: Save turbo cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('package-lock.json') }}
